# Generated by Django 3.1.1 on 2020-09-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_textfield', models.TextField()),
                ('is_malisious', models.BooleanField(default=False)),
            ],
        ),
    ]
