# Generated by Django 3.1.1 on 2020-09-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
